version: "3"

services:
  app:
    container_name: "bookshare"
    image: "bookshare:latest"
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=admin
    ports:
      - "8080:8080" # application
      - "9990:9990" # admin console