package MotoHafty.domain;

public enum Province {

    DOLNOŚLĄSKIE,
    KUJAWSKO_POMORSKIE,
    LUBELSKIE,
    ŁÓDZKIE,
    MAŁOPOLSKIE,
    MAZZOWIECKIE,
    OPOLSKIE,
    PODKARPACKIE,
    POLDASKIE,
    POMORSKIE,
    ŚLĄSKIE,
    ŚWIĘTOKRZYSKIE,
    WARMIŃSKO_MAZURSKIE,
    WIELKOPOSKIE,
    ZACHODNIOPOMORSKIE,
    OTHER
}
